apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ffmpeg
  labels:
    app: ffmpeg-deployment
spec:
  selector:
    matchLabels:
      service: ffmpeg
  template:
    metadata:
      labels:
        app: ffmpeg-deployment
        service: ffmpeg
    spec:
      tolerations:
        - key: type
          operator: Equal
          value: backend
          effect: NoSchedule
      containers:
        - name: ffmpeg
          image: livestream.azurecr.io/ffmpeg
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 4
              memory: 8Gi
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
