apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-plane
automountServiceAccountToken: true
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: control-plane
  namespace: default
subjects:
- kind: ServiceAccount
  name: control-plane
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: channels
  labels:
    app: channel-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      service: channels
  template:
    metadata:
      labels:
        app: channel-deployment
        service: channels
    spec:
      nodeSelector:
        agentpool: system
      serviceAccountName: control-plane
      containers:
        - name: channels
          image: livestream.azurecr.io/kubeclient
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: channels
  labels:
    app: channel-deployment
    service: channels
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: channels