apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: frontend
  labels:
    app: frontend-deployment
spec:
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        app: frontend-deployment
    spec:
      nodeSelector:
        type: frontend
      tolerations:
      - key: "type"
        operator: Equal
        value: frontend
        effect: NoSchedule
      containers:
        - name: nginx
          image: livestream.azurecr.io/nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 1935
              protocol: TCP
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend-deployment
    service: nginx
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: rtmp
      port: 1935
      targetPort: 1935
      protocol: TCP
  selector:
    service: frontend
  type: LoadBalancer